### ISSUE TITLE
October 2023: Finalize schedule

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/reproducible-research#122]
This issue tracks finalizing the schedule.
Make sure to add all slide PDFs as part of #120!

**Comment by jaclyn-taroni** [comment]
The current schedule allots 15 minutes to walk from the hotel to dinner. The walk from the Inn at Penn to Harper's Garden is _at least 30 minutes_, which may not be practical if it is pouring, etc.

**Comment by Jen-OMalley** [comment]
> The current schedule allows 15 minutes to walk from the hotel to dinner. The walk from the Inn at Penn to Harper's Garden is _at least 30 minutes_, which may not be practical if it is pouring, etc.

I would suggest meeting in the lobby by 5:30 and perhaps we should say "walk or Lyft."

**Comment by sjspielman** [comment]
Don't forget link to data sharing slides!
