### ISSUE TITLE
October 2023: git authentication setup

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/reproducible-research#125]
Wondering if we want to add `ssh` key setup or something into the github setup instructions. Maybe a good approach is to explain the benefits and link to github instructions for it? Or 🌶️ suggest 1Password 🎉 (just leaving [wsl2 info](https://gist.github.com/WillianTomaz/a972f544cc201d3fbc8cd1f6aeccef51) here for posterity) (probably not though, we don't want to suggest to folks that they _must_ pay for a product, I just love really love the ssh agent so a name drop at least is maybe merited...)

Any thoughts on updating setup docs, @jashapiro?

**Comment by jashapiro** [comment]
Since in this course we are using GitKraken, which handles everything with OAUTH, I think, so there should not be any need for SSH keys. I think most of the benefits are outside the scope of an intro, but maybe you something particular in mind?

**Comment by sjspielman** [comment]
> maybe you something particular in mind?

Truly, I do not! My thought process was, I had a faint memory that github was going to start requiring ssh for everything, but then realized I had probably confused that with the 2fa requirement. But at that point ssh was on my mind, so I suppose this issue notes for posterity that I thought of it in passing...

**Comment by sjspielman** [comment]
Closing as not needed!
