### ISSUE TITLE
Add data sharing links to resources

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/reproducible-research#127]
Just dropping the link to the [DMPTool](https://dmptool.org/) (Data Management Planning Tool). May be another resource to consider sharing? People can use this to find the [NIH default template](https://dmptool.org/public_templates?page=1&search=nih) and a [variety of data management plans](https://dmptool.org/public_plans?search=nih&sort_by=created_at) submitted by other NIH-funded researchers to reference.

Ooh side note! Perhaps, we may want to add the relevant resources we share during RRP to the [data and resource sharing section](https://www.ccdatalab.org/research-resources#data-sharing) of our research resources page on ccdatalab.org.

_Originally posted by @Jen-OMalley in https://github.com/AlexsLemonade/reproducible-research/issues/117#issuecomment-1741011164_

**Comment by Jen-OMalley** [comment]
Noting that I added 2 resources to [this page](https://www.ccdatalab.org/research-resources) today - DMPTool and Open Science Framework
