### ISSUE TITLE
UNIX slides errors

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/reproducible-research#142]
For the examples in slide 9, we started with the box indicating which file we were talking about started in the wrong spot (has since been deleted), and the wrong file extension was used for the `00-process-stuff` file in the first "answer."

**Comment by sjspielman** [comment]
fixed ✅ 
https://docs.google.com/presentation/d/1WPXkItJZEUXMY20cLrdMXHiBC2PyunR14RUSDg4nfIc/edit#slide=id.g290a84fd9e9_0_1
