### ISSUE TITLE
Add OpenRRP schedule

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/reproducible-research#147]
This issue tracks updating the schedule for May 14-15th 2024's OpenRRP workshop.

**Comment by sjspielman** [comment]
See spreadsheet for schedule plan: https://docs.google.com/spreadsheets/d/16ELOVKidkNkpR2_DJzp-nOEiUJ9TTTOwHmGtQ_-enZE/edit?usp=sharing

**Comment by sjspielman** [comment]
@Jen-OMalley are we planning on a dinner here?

**Comment by Jen-OMalley** [comment]
@sjspielman Yupp! Le Bus (4201 Ridge Ave, Philadelphia, PA 19129) on Tuesday, May 14 at 5:45pm.
