### ISSUE TITLE
OpenRRP: Slides for code review

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/reproducible-research#149]
This issue tracks writing the slides that introduce code review for Day 2 of OpenRRP. Much of this content can be adapted from our [github code review workshop slides](https://github.com/AlexsLemonade/2023-chop-training).

Slides should also include content on merging and post-merge steps.

**Comment by jaclyn-taroni** [comment]
@sjspielman and @jashapiro - ready for your feedback: https://docs.google.com/presentation/d/1aqIn8qmn7ijwgVzFd6mtfxBTD6UPEKaLOxOQNyMYUQs/edit?usp=sharing

**Comment by sjspielman** [comment]
Slides look good to me, I had no comments!

**Comment by jashapiro** [comment]
LGTM!

**Comment by jaclyn-taroni** [comment]
I will call this done, in that case!
