### ISSUE TITLE
OpenRRP: Conda slides

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/reproducible-research#151]
This issue tracks writing a few slides to introduce conda usage and installation/setup steps. Participants will have seen `renv` discussed on day 1 of the workshop, so these slides should provide a comparable conceptual introduction to conda.

We will use this slides during the OpenScPCA setup in #150.

**Comment by jashapiro** [comment]
Slides are up for review at https://docs.google.com/presentation/d/1RsDIR2wtfIkdwg6FDJghlZl9qrwuICmupMrDNTKOAjw/edit?usp=sharing

@sjspielman

**Comment by jashapiro** [comment]
Considering these done
