### ISSUE TITLE
Create slides and instructor notes for using git, git init, and tokens on a server

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/reproducible-research#179]
We already have some notes about using git at the command line in notes, but for the upcoming training, we want to be able to integrate these activities into some of our ["regular" training modules](https://github.com/AlexsLemonade/training-modules).

To do this, we will want to show people a few new things that we need to make some slides and instructor notes for:

- Creating a Personal Access Token (PAT)on Githhub to use git with `https` from the command line.
  - This should include showing how to set tokens to expire as good practice: for this case we can make a token that expires after 7 days, so people don't make one that lives past the time of the course
  - Using the R `gitcreds` package to store the token on the server (First investigate is it stored?)
  - Alternatively: We could show creating/using an SSH key with `ssh-keygen` (specifically `ssh-keygen -t ed25519` for current best practice); I had meant to mention this possibility, but I am not sure which is really easier? For SSH they need to create and store another password somewhere. Thoughts @sjspielman @jaclyn-taroni?

- Using `git init` to turn an existing folder into a repository
  - [Instructions for making a new repo and pushing it to GH](https://docs.github.com/en/migrations/importing-source-code/using-the-command-line-to-import-source-code/adding-locally-hosted-code-to-github). In summary:
    - Run `git init`
    - Add files with `git add .` Our instructions will be sure to note looking at the `.gitignore` file beforehand
    - `git commit -m "First commit"`
    - Create repo on GitHub, but _do not_ let the robot make any files
    - copy the repo address
    - `git remote add origin {REMOTE-URL}`
    - `git push -u origin main`

Finally, we will want to add to our notes that in addition to saving at the end of each module, we should encourage people to `git add` the file they have been working on and/or the rendered notebook, then use `git commit -m` and `git push` to save a copy on the server.

**Comment by jaclyn-taroni** [comment]
I think using `gitcreds` to create a token that expires after the duration of the course is probably a better option than SSH.

**Comment by sjspielman** [comment]
> I think using gitcreds to create a token that expires after the duration of the course is probably a better option than SSH.

While I don't feel _very_ strongly, I do tend to agree with this.

**Comment by sjspielman** [comment]
Update: We've found that a git credentials cache with timeout is required for using a token on the server, which means that at each timeout, participants will have to enter their re-token. This in turn means they'd have to store it in plain text somewhere, which we'd like to avoid. So, perhaps ssh is the move.

**Comment by jashapiro** [comment]
The issue with ssh is they will have to enter their key password on every push unless they add them to ssh-agent, which we don't seem to have fully set up on the server. So it is a bit of a quandary...

I think maybe telling people to keep their GH token in a password manager or on their local machine is probably still better, especially if we have tokens that expire after a week. By better I mean we can talk about security, and get people thinking about it.

**Comment by sjspielman** [comment]
Instructor notes were written in #182. Slides still need to be made to close this out.

**Comment by sjspielman** [comment]
@jashapiro I've drafted up some slides here for this, please let me know any feedback! https://docs.google.com/presentation/d/15ZNx7K05yXqi4NSb-AlLF_n8-vwfX4iG3dZ84tbQlAI/edit?usp=sharing

**Comment by sjspielman** [comment]
Thanks for feedback @jashapiro! responded to your slide comments if you want to take another pass.

**Comment by sjspielman** [comment]
Slides have now been made and reviewed, and the PDF is in the workshop repo.
