### ISSUE TITLE
2024 August: Review RRP materials

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/reproducible-research#183]
This issue tracks reviewing existing RRP materials, including slides and instructor notes, ahead of our workshop in August 2024. We should divide these up based on who teaches each bit as follows:

### @sjspielman items
- [x] Why does reproducibility matter? (slides)
- [x] Strategies for data sharing (slides) [EDIT: still check these slides, but we're not necessarily planning to use them]
- [x] Introduction to UNIX and the command line
    - [x] Slides
    - [x] Instructor notes
    - [ ] UNIX cheatsheet
- [x] Shell scripting
    - [x] Slides
    - [x] Instructor notes
    - [x] The script still works (aka the data didn't move again..)
- [x] The Git stage/commit/push workflow
    - [x] Slides
    - [x] Instructor notes
- [x] Working with branches in Git
    - [x] Slides
    - [x] Instructor notes
    
### @jashapiro items

- [x] Project organization (slides)
- [x] Introduction to Git; Forking and cloning a repository
    - [x] Slides
    - [ ] Instructor notes
- [x] Organizing code in scripts and notebooks
    - [x] Slides
    - [x] Instructor notes
- [x] Managing packages and environments 
    - [x] Slides
    - [x] Instructor notes

**Comment by sjspielman** [comment]
I've gone over all materials here and everything is in good shape. I made a few changes to slides:

- I've never loved the legibility of [slides 7 & 9 here](https://docs.google.com/presentation/d/1SDUyYVNgvDDRodVqmDQPVQ5wnjQesWfBTg0EAcdbcSo/edit#slide=id.g12c5d635c71_0_91), so I tried an improvement/
- I hid the git CLI slides from [this deck](https://docs.google.com/presentation/d/1_YckNhAkp_82PKR6PGS5SdaKDgoueYVTXaPi5pQV9ik/edit#slide=id.p) since we're going to talk about it more when we set up git on RStudio Server. I figured it was best to skip those slides here and introduce them when we actually introduce git command line as part of #179

**Comment by jashapiro** [comment]
I have reviewed my slides and everything looks good to me. I am closing this now.
