### ISSUE TITLE
2024 August issues

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/reproducible-research#184]
Using to track RRP issues that come up during the 2024 August workshop.

**Comment by jaclyn-taroni** [comment]
Slide 9 in the intro to motivation slides: "your" -> "you're" in the first sub bullet point

**Comment by sjspielman** [comment]
We need to have them install pandoc if we want to knit from terminal. Otherwise, update instructor notes to only knit from RStudio.

**Comment by sjspielman** [comment]
We need to specify posix (or none) line endings for Windows folks in RStudio. The setting is in Global Options > Code > Saving.

**Comment by jashapiro** [comment]
> The slide introducing braces in the shell scripting slides shows code that doesn't work - because it needs braces!

I'm not sure I see this? All the code looks right to me, except for the `$CONTENT` that should be `$VARIABLE_NAME` (and has been changed on google slides)

**Comment by jaclyn-taroni** [comment]
The skel setup script removes the module-specific `.gitignore` files (https://github.com/AlexsLemonade/training-admin/blob/7eb216ff07ca4b40f93bea104ef1f27916ee106a/scripts/setup-skel.sh#L70). This is a problem for the initialization of the Git repo on RStudio Server.

**Comment by sjspielman** [comment]
All slide-related comments here have been addressed, and other comments have been broken out into their own issues.
