### ISSUE TITLE
2024 October: Update slides

### ISSUE THREAD

**Issue by Jen-OMalley** [AlexsLemonade/reproducible-research#187]
This issue will track updating slides.

| What is it? | Who is responsible? | Is it done? |
|------------|---------------------|------------|
| Workshop welcome and introductions | Josh |  ✅ |
| Introduction to reproducible research practices | Jackie | ✅  |
|  Project organization | Josh |✅ |
| Introduction to UNIX and the command line | Jackie | ✅  |
| Introduction to Git / Forking and cloning | Josh | ✅|
| Shell scripting part I | Jackie | ✅ |
| Shell scripting part II | Jackie | ✅  |
| Git stage/commit/push | Jackie | ✅  |
| Organizing code in scripts and notebooks | Josh |✅ |
| Managing packages and environments | Josh | ✅|
| Working with branches | Josh |✅ |

_If there are no slides associated with a lesson, check it off for free!_

**Comment by jashapiro** [comment]
All done, though maybe @Jen-OMalley wants to have a look at the intro slides in case I missed anything? https://docs.google.com/presentation/d/1JLCiAbE8RBNQ0yc81Ui5Jf6IeAzpwf-HtECWCpvNVI0/edit#slide=id.p

**Comment by Jen-OMalley** [comment]
Oops! Realizing that breakfast is not on the schedule. I think that's okay as long as we tell people. If you want to add it to the slides, it will be available starting at 8:30am on Thursday. Otherwise LGTM!

**Comment by jaclyn-taroni** [comment]
Let's change the schedule, too, please.

**Comment by Jen-OMalley** [comment]
Sure. I'll do that!

**Comment by Jen-OMalley** [comment]
Nvm! Josh beat me to it.

**Comment by jashapiro** [comment]
Done and done!
