### ISSUE TITLE
Organizing your Rscript

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/reproducible-research#25]
Breaking up #21. This is related to #18. 

We want to cover where to put libraries and file paths and to make sure we cover `optparse`. Specifically, we want to create an Rscript that accepts a data table of some kind and performs some processing (e.g., with the `tidyverse`) to prepare for visualization in a subsequent notebook.

The scope of this issue also includes identifying the data tables we want to use – we need at least two that can be used with this script – and as such, sketching out some ideas about what to do in the subsequent notebook.

**Comment by sjspielman** [comment]
Closing with #84 and  https://github.com/AlexsLemonade/rrp-workshop-exercises/pull/3.
