### ISSUE TITLE
Using an R Notebook to document your analysis and visualization

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/reproducible-research#27]
Breaking up #21. This is also related to the literate programming part of #12. 

Create an R Notebook to analyze and visualize the data that we preprocessed with an Rscript.

The scope of this issue should perhaps include some slides that introduce the concepts of computational notebooks (and when to use them) so I've marked it with `slides/talking points` for now

**Comment by sjspielman** [comment]
Closing with #84 and https://github.com/AlexsLemonade/rrp-workshop-exercises/pull/6
