### ISSUE TITLE
One set of slides to rule them all

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/reproducible-research#34]
_After_ all slides have been developed, it may be more convenient to stitch all slides together with section dividers so we can disseminate one set of slides throughout the day. In my experience one set of slides provides trainees with a more convenient/concise reference (only 1 PDF slide deck), and it's easier for trainers to launch one slide deck for the whole day.

**Comment by jashapiro** [comment]
I'm going to suggest we commit this pdf to `docs/resources` so that we can easily link to it from the course website.

**Comment by jashapiro** [comment]
closed by #98
