### ISSUE TITLE
Intro Slides 2: Motivation and discussion

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/reproducible-research#51]
After the logistical intro, we will want to move into introducing the content. This set of slides should include overall motivation for reproducibility. 

Some general thoughts of points we should hit:
- What do we mean by reproducibility? (vs. replication?)
- What are the benefits? 
  - To you, to collaborators, to the community, 
  - What are the some pitfalls it may help you avoid?  
  - Mention funder requirements?
- How much do you need to do?
  - Emphasize iterative process; some is better than none! 
  - ABD: always be documenting
  -  Publish your code, it is good enough

We can adapt some content here from https://www.repro4everyone.org/resources/intro-reproducibility

This section should include room for discussion! We want people to come up with ideas as much on their own as for us to provide them.

**Comment by sjspielman** [comment]
Slides have been reviewed by all!
