### ISSUE TITLE
Update `0n` file names

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/reproducible-research#78]
In `workshop_materials/slides/` and `instructor_notes`, some files are named `0n` due to uncertainty about the final order at the time when those items were originally added. We need to rename these files with their appropriate order before launch.

**Comment by sjspielman** [comment]
There are no `0n` file names at this point, so this issue can be closed!

**Comment by jashapiro** [comment]
I agree with keeping the numbers & names matching the associated slide decks.

**Comment by sjspielman** [comment]
Closed with #93
